apiVersion: apps/v1
kind: Deployment
metadata:
  name: week6passtask-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: week6passtask
  template:
    metadata:
      labels:
        app: week6passtask
    spec:
      containers:
        - name: week6passtask
          image: week6passtask:v2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
